Add english translation to the maintenance page
fccn/nau-maintenance-site pull request #1
Opened 2024-01-29 16:58 UTC by sandroscosta

This PR adds english strings that display when the browser language is defined as anything but Portuguese.

2024-02-05 14:28 UTC, igobranco requested changes
We also need a combo box, or links, to change the language. On NAU we are using a combo box, so I think the best approach is to use a combo box.

Example, view memorial of Arquivo.pt:
Archived site: https://www.mundonaescola.pt/

Old code of memorial:
https://github.com/arquivo/memorial/blob/3bab4e1033116383d789aa6100c218552faf954e/templates/redirect_default.html

New code, that uses jQuery ( ugly ):
https://github.com/arquivo/memorial/blob/master/templates/redirect_default.html

I think the best approach is to have different data language attributes and replace the text of the element using JS. Each element has a `data-lang-pt` and `data-lang-en` and on page load run a JS function that updates each element text - dependent of the browser language  or by the `nau-language-preference` cookie - choose a different language to display.

2024-02-05 14:28 UTC, igobranco commented on site/index.html
> +        if (navigatorLanguage != 'pt'){
Please create an Key-Value structure with each translation.
```
messages = {
    pt: {
        title: 'Em manutenção',
        shortmessage: 'We are updating the NAU platform.<br>We promise it will be quick!'
    },
    en: {
        title: 'Under maintenance',
        shortmessage: 'Estamos a atualizar a plataforma NAU.<br>Prometemos que vai ser rápido!'
    }
}

# Then access like:
messages['pt']['title']
messages.pt.title

# access if it is pt or en like `navigatorLanguage == 'pt' ? 'pt' : 'en'`.

```

2024-02-05 14:28 UTC, igobranco commented on site/index.html
> -        <div class="op-details" style="display:none;">
Add a JS boolean flag to show or hide the short message.

2024-02-15 14:46 UTC, sandroscosta commented on site/index.html
> -        <div class="op-details" style="display:none;">
Forgot about this. Let me update it with a flag.

2024-02-15 15:10 UTC, sandroscosta commented
> dependent of the browser language or by the `nau-language-preference` cookie - choose a different language to display.

This is a really nice idea. I'll rework logic to check if a language preference is set in the cookie and choose it over the navigator. If it doesn't exist, it'll use the navigator language.

2024-02-15 21:50 UTC, igobranco approved these changes
It's much better! Almost there!

Please view my comments, they are just more my preference.

2024-02-15 21:50 UTC, igobranco commented on site/index.html
> +                            href="https://ajuda.nau.edu.pt">https://ajuda.nau.edu.pt</a></p>
Rmove the *https://* text on ajuda.nau.edu.pt anchors.

2024-02-15 21:50 UTC, igobranco commented on site/index.html
> +        <p class="website"><a href="https://ajuda.nau.edu.pt">https://ajuda.nau.edu.pt</a></p>
Remove the *https://* text on ajuda.nau.edu.pt anchors.

2024-02-15 21:50 UTC, igobranco commented on site/index.html
> +        <section class="social">
The social network links, in the bottom, should be aligned to the middle.

2024-02-15 21:50 UTC, igobranco commented on site/index.html
> +            <button id="changeLang" class="change-lang-link" aria-label="Mudar língua para Português">Português</button>
I think will be best if he language changer would be the first content, aligned to the right.

2024-02-16 10:46 UTC, igobranco commented
LGTM ✔️

2024-02-16 10:51 UTC, merged